[package]
name = "lavalink-rs"
version = "0.8.0"
authors = ["vicky5124 <vickyf5124@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Lavalink (and andesite) bindings for discord bot crates"
readme = "README.md"
homepage = "https://gitlab.com/vicky5124/lavalink-rs/"
repository =  "https://gitlab.com/vicky5124/lavalink-rs/"
keywords = ["lavalink", "discord", "serenity", "twilight", "tokio"]
categories = ["multimedia"]
documentation = "https://docs.rs/lavalink-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

rustls-marker = []
native-marker = []
tokio-02-marker = []
andesite = []

serenity = ["serenity-dep"]
twilight = ["twilight-model"]

rustls = [
    "async-tungstenite/tokio-rustls",
    "songbird/gateway",
    "tokio",
    "tokio-rustls",
    "reqwest",
    "reqwest/rustls-tls",

    "rustls-marker"
]

native = [
    "async-tungstenite/tokio-native-tls",
    "songbird/gateway",
    "tokio",
    "tokio-native-tls",
    "reqwest",
    "reqwest/native-tls",

    "native-marker"
]

rustls-tokio-02 = [
    "async-tungstenite-compat/tokio-rustls",
    "songbird/gateway-tokio-02",
    "tokio-compat",
    "tokio-rustls-compat",
    "reqwest-compat",
    "reqwest-compat/rustls-tls",

    "rustls-marker",
    "tokio-02-marker"
]

native-tokio-02 = [
    "async-tungstenite-compat/tokio-native-tls",
    "songbird/gateway-tokio-02",
    "tokio-compat",
    "tokio-native-tls-compat",
    "reqwest-compat",
    "reqwest-compat/native-tls",

    "native-marker",
    "tokio-02-marker"
]

[package.metadata.docs.rs]
features = ["rustls", "twilight", "serenity", "andesite"]

[dependencies]
regex = "1.3"
serde_json = "1.0"
serde-aux = "2"
futures = "0.3"
tracing = "0.1"
tracing-log = "0.1"
http = "0.2"
typemap_rev = "0.1"
dashmap = "4"
async-trait = "0.1"

[dependencies.tokio]
version = "1"
default-features = false
features = ["rt-multi-thread", "sync", "time"]
optional = true

[dependencies.tokio-compat]
package = "tokio"
version = "0.2"
default-features = false
features = ["rt-threaded", "sync", "time"]
optional = true

[dependencies.tokio-native-tls]
version = "0.3"
optional = true

[dependencies.tokio-native-tls-compat]
package = "tokio-native-tls"
version = "0.1"
optional = true

[dependencies.tokio-rustls]
version = "0.22"
optional = true

[dependencies.tokio-rustls-compat]
package = "tokio-rustls"
version = "0.14"
optional = true

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json"]
optional = true

[dependencies.reqwest-compat]
package = "reqwest"
version = "0.10"
default-features = false
features = ["json"]
optional = true

[dependencies.async-tungstenite]
version = "0.13"
default-features = false
features = ["tokio-runtime"]
optional = true

[dependencies.async-tungstenite-compat]
package = "async-tungstenite"
version = "0.9"
default-features = false
features = ["tokio-runtime"]
optional = true

[dependencies.serenity-dep]
package = "serenity"
version = "0.10"
default-features = false
features=["model"]
optional = true

[dependencies.twilight-model]
version = "0.3"
optional = true

[dependencies.songbird]
version = "0.1"
default-features = false

[dev-dependencies.tokio]
version = "1"
features = ["full"]

[dev-dependencies.serenity-dep]
package = "serenity"
version = "^0.10.2"
features = ["client", "cache", "standard_framework", "voice"]

[dev-dependencies.songbird]
version = "^0.1.3"
default-features = false
features = ["serenity-rustls", "gateway"]

[dev-dependencies.tracing]
version = "0.1"

[dev-dependencies.tracing-subscriber]
version = "0.2"

[build-dependencies]
version_check = "0.9"
