[package]
name = "lavalink-rs"
version = "0.9.0-rc.1"
authors = ["vicky5124 <vickyf5124@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Lavalink (and andesite) bindings for discord bot crates"
readme = "README.md"
homepage = "https://gitlab.com/vicky5124/lavalink-rs/"
repository =  "https://gitlab.com/vicky5124/lavalink-rs/"
keywords = ["lavalink", "discord", "serenity", "twilight", "tokio"]
categories = ["multimedia"]
documentation = "https://docs.rs/lavalink-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["rustls", "songbird", "tracing-log"]

tokio-02-marker = []
andesite = []
simple-gateway = []

tracing-log = ["tracing"]
normal-log = ["log"]

serenity = ["serenity-dep"]
twilight = ["twilight-model"]
songbird = ["songbird-dep"]

rustls = [
    "async-tungstenite/tokio-rustls-webpki-roots",
    "tokio-rustls",
    "reqwest/rustls-tls",
]

native = [
    "async-tungstenite/tokio-native-tls",
    "tokio-native-tls",
    "reqwest/native-tls",
]

[package.metadata.docs.rs]
features = ["rustls", "twilight", "serenity", "andesite", "songbird", "simple-gateway"]

[dependencies]
regex = "1.3"
serde_json = "1.0"
serde-aux = "2"
futures = "0.3"
http = "0.2"
typemap_rev = "0.1"
dashmap = "4"
async-trait = "0.1"

[dependencies.tokio]
version = "1"
default-features = false
features = ["rt-multi-thread", "sync", "time"]

[dependencies.tokio-native-tls]
version = "0.3"
optional = true

[dependencies.tokio-rustls]
version = "0.22"
optional = true

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json"]

[dependencies.async-tungstenite]
version = "0.15"
default-features = false
features = ["tokio-runtime"]
optional = true

[dependencies.serenity-dep]
package = "serenity"
version = "0.10"
default-features = false
features=["model"]
optional = true

[dependencies.twilight-model]
version = "0.6"
optional = true

[dependencies.songbird-dep]
package = "songbird"
version = "0.2"
default-features = false
features = ["gateway"]
optional = true

[dependencies.tracing]
version = "0.1"
optional = true

[dependencies.log]
version = "0.4"
optional = true

[dev-dependencies.tokio]
version = "1"
features = ["full"]

[dev-dependencies.serenity-dep]
package = "serenity"
version = "^0.10.2"
features = ["client", "cache", "standard_framework", "voice"]

[dev-dependencies.songbird-dep]
package = "songbird"
version = "0.2"
default-features = false
features = ["serenity-rustls", "gateway"]

[dev-dependencies.tracing]
version = "0.1"

[dev-dependencies.tracing-subscriber]
version = "0.2"

[build-dependencies]
version_check = "0.9"
