[package]
name = "lavalink-rs"
version = "0.10.0-alpha.2"
edition = "2021"
authors = ["vicky5124 <vickyf5124@gmail.com>"]
license = "MPL-2.0"
description = "Lavalink API wrapper for discord audio playing"
readme = "README.md"
homepage = "https://gitlab.com/vicky5124/lavalink-rs/"
repository =  "https://gitlab.com/vicky5124/lavalink-rs/"
keywords = ["lavalink", "discord", "serenity", "songbird", "tokio"]
categories = ["multimedia"]
documentation = "https://docs.rs/lavalink-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1"
serde_json = "1"
dashmap = "5"
http = "0.2"
tracing = "0.1"
futures = "0.3"
url = "2"
oneshot = "0.1"

[dependencies.async-tungstenite]
version = "0.23"
features = ["tokio-rustls-webpki-roots"]

[dependencies.tokio]
version = "1"
features = ["sync"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.reqwest]
version = "0.11"
features = ["json"]
