[package]
name = "serenity-lavalink"
version = "0.0.1"
authors = ["nitsuga5124 <nitsuga5124@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3"
serde_json = "1.0"
tracing-log = "0.1"
tokio-tls = "0.3"
http = "0.2"
futures = "0.3"

[dependencies.tokio]
version = "0.2.13"
features = ["full"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.reqwest]
version = "*"
features = ["json"]

[dependencies.async-tungstenite]
default-features = false
features = ["tokio-runtime", "tokio-tls"]
version = "0.4"

[dependencies.serenity]
git = "https://github.com/Lakelezz/serenity/"
branch = "await"
default-features = false
features = ["cache", "gateway", "http", "model", "native_tls_backend", "absolute_ratelimits", "voice"]
